### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by yujialele** [GeWu-Lab/Sounding-Object-Segmentation-Preference#1]
Thank you for your better work! Please provide the paper link or your manuscript. I don't find the preprinted version in the internet. Thanks!

**Comment by yaotingwangofficial** [comment]
Thanks for your attention, we will upload to arxiv after camer-ready (15th July).

**Comment by yaotingwangofficial** [comment]
https://www.arxiv.org/abs/2407.10947

and also please visit our relative project [RefAVS dataset ](https://gewu-lab.github.io/Ref-AVS/)
